build:
		gcc main.c ./src/arithematicOperations/addition.c ./src/arithematicOperations/substraction.c ./src/arithematicOperations/division.c ./src/arithematicOperations/multiplication.c ./src/calculator/applyOperation.c ./src/calculator/evaluate.c ./src/calculator/precedence.c -o calculator

run:
		./calculator

clean: 
		rm calculator
